### ISSUE TITLE
getCommitsSince has a (currently-)pointless parameter

### ISSUE THREAD

**Issue by textbook** [CodeYourFuture/github-tracker#1]
https://github.com/haroon-ali-dev/google-sheets-tracker/blob/e3873c2816d09088587e826f4ff177e23c741e6e/gitHub.js#L7-L13

The question that immediately occurs to me when I read a condition like that is: what if `timeFrame !== "one-week-ago"`\*? If a function can only operate properly for a single one of all of the possible values of a parameter, it probably shouldn't be a parameter at all. That implies a level of reusability the function simply doesn't deliver on; every time you want to pass in a new value, you have to _edit_ the function to deal with that.

Then there's the _value_ of the parameter, `"one-week-ago"`. This might make sense if this was _user input_, for example if it was coming from a CLI:

```bash
$ get-commits --since 'one-week-ago'
```
or configuration file or something. But it's not, it's being passed by another part of the same program. (And even if it was external configuration or user input, I would parse it in `cli.js`, at the _edge_ of the program, then pass a more useful value around inside.)

I assume this is based on [my suggestion](https://gist.github.com/textbook/b01549ac27acee85cf03b64358938009) to do something like:

```js
    for (const user of users) {
        commits.push(await github.getCommitsSince(user, oneWeekAgo()));
    }
```

I deliberately didn't include the return value of `oneWeekAgo`, but the point of the function was to illustrate that it shouldn't be the responsibility of `github.js` to decide the relevant timeline. That makes it much more resuable (e.g. for getting the last 28 days' worth of commits, to calculate an average). Think about how you're representing this _in `github.js`_, maybe _that_ should be the input?

---

\* _In simple practical terms, the answer to the question is: `url` remains `undefined`, which doesn't make sense as an input to `fetch`. In the browser it seems to attempt to use it anyway, stringifying the value then treating it as a relative path to your current origin. For example if you're on `https://example.com/foo/bar` and try to `fetch(undefined)`, it'll make a request to `https://example.com/foo/undefined`. In Node you get something like `Uncaught TypeError: Failed to parse URL from undefined`._

**Comment by haroon-ali-dev** [comment]
I will try my best to implement this with the team very soon. Thank you.
